### ISSUE TITLE
Can't see minutes on clock [android]

### ISSUE THREAD

**Issue by psynyde** [asheeeshh/onigiri#1]
As the title says can't see the minute clock on bromite(chromium fork & possibly same result with chrome).
**Device:** Nokia 8.1 (a11)
**Browser:** Bromite (Version 101.0.4951.53)
**Screen resolution:** 1080 x 2280 pixels, 19:9 ratio
<details> <summary>preview👀</summary>
<img src="https://user-images.githubusercontent.com/75927811/167776937-4438cc8d-dcf6-43ba-bd92-0ea68171a705.png" />
</details>

**Comment by asrvd** [comment]
I tried reproducing the issue but it works just fine, could you please check if its working fine on other browsers, I'm using chrome and it looks like this for me: 

![ss](https://hdmlbxshrurxrggmrogp.supabase.co/storage/v1/object/public/gpic/v1/image_2021_pxPjrvipuo)

**Comment by psynyde** [comment]
> I tried reproducing the issue but it works just fine, could you please check if its working fine on other browsers, I'm using chrome and it looks like this for me: 

hm chrome does supports the clock perfectly but other chromium bowsers seems to have this bug..tried on `firefox`, `kiwi` (android chrome with extensions) & original `chromium`..all seems to have similar issue.maybe its related to the screen resolution as chrome handles screen resolution differently than others..maybe tweaking some pixel values on media query will fix the issue..i highly suggest you to use firefox for your dev  environment

**Comment by asrvd** [comment]
> > I tried reproducing the issue but it works just fine, could you please check if its working fine on other browsers, I'm using chrome and it looks like this for me:
> 
> hm chrome does supports the clock perfectly but other chromium bowsers seems to have this bug..tried on `firefox`, `kiwi` (android chrome with extensions) & original `chromium`..all seems to have similar issue.maybe its related to the screen resolution as chrome handles screen resolution differently than others..maybe tweaking some pixel values on media query will fix the issue..i highly suggest you to use firefox for your dev environment

thanks for testing it, I will try to look into this and fix it if possible , I'm thinking of using firefox for dev actually, thanks for the suggestion :)

**Comment by asrvd** [comment]
@WahidIslamLinad I tried testing it myself, I even tested i on chromium but it looks just fine for me

 edit: one of my friend was facing the same issue, and I figured out that the bug was due to `intl` so I replaced it with `Date()` instead and everything works fine now! Can you test once again and let me know if it worked? thanks.

**Comment by psynyde** [comment]
> Can you test once again and let me know if it worked? thanks.

hm i tested it now it works fine on all platform ❤️
now only left to do is maybe add settings to the page & save them to local storage 🤔 ..Alright then so as the bug fixed maybe we should close this issue, btw thnx for quick response ❤️

**Comment by asrvd** [comment]
> > Can you test once again and let me know if it worked? thanks.
> 
> hm i tested it now it works fine on all platform ❤️ now only left to do is maybe add settings to the page & save them to local storage 🤔 ..Alright then so as the bug fixed maybe we should close this issue, btw thnx for quick response ❤️

yes I'm planning to add more features soon, local settings is one of them :)
thanks for pointing out the issue.
